(()=>{
'use strict';
const QL=window.QuantoLabTools;const {money,number,pct,clamp,n,irrfMonthly,cltPackageApprox,pjEquivalentClt}=QL.util;const SOURCES=QL.sources;
QL.register({
'pj-clt-equivalente':{fields:[['pj','Faturamento PJ por mês','number',10000,'R$','',100,'monthlyIncome','Valor bruto mensal do contrato PJ.'],['meses','Meses faturados por ano','number',12,'',' meses',1,null,'Reduza se houver meses sem faturamento.'],['impostos','Impostos efetivos sobre faturamento','number',10,'','%',.1,'taxRate','Informe sua alíquota efetiva estimada.'],['custos','Custos PJ por mês','number',500,'R$','',50,'monthlyCosts','Contabilidade, ferramentas, plano de saúde e outros custos.']],source:SOURCES.methodology,related:[['/comparador-profissional','Comparar proposta CLT e PJ'],['/impostos-pj','Detalhar impostos PJ'],['/pro-labore','Simular pró labore']],validate:v=>n(v,'pj')<=0?'Informe o faturamento mensal como PJ.':'',calc:v=>{const pj=n(v,'pj'),months=clamp(n(v,'meses',12),1,12),tax=n(v,'impostos'),costs=n(v,'custos'),annual=pj*months*(1-tax/100)-costs*12,clt=pjEquivalentClt(Math.max(0,annual));return {headline:money(clt),summary:'Salário CLT bruto mensal de referência cujo pacote anual aproximado se aproxima do valor PJ disponível informado.',rows:[['PJ disponível estimado no ano',money(annual)],['Pacote CLT anual aproximado',money(cltPackageApprox(clt))],['Equivalente CLT bruto mensal',money(clt)]],note:'É uma equivalência de pacote, não de dinheiro líquido. Benefícios, riscos, tributação e condições contratuais podem mudar a decisão.'};}},
'impostos-pj':{fields:[['faturamento','Faturamento mensal','number',10000,'R$','',100,'monthlyIncome','Receita bruta mensal usada na simulação.'],['aliquota','Alíquota efetiva estimada','number',10,'','%',.1,'taxRate','Use sua alíquota efetiva real ou uma estimativa validada com sua contabilidade.'],['contador','Contabilidade por mês','number',250,'R$','',10,null,'Custo mensal do serviço contábil.'],['outros','Outros custos PJ','number',300,'R$','',10,'monthlyCosts','Ferramentas, taxas e despesas recorrentes.']],source:SOURCES.methodology,related:[['/pro-labore','Simular pró labore'],['/mei-das','Ver DAS MEI'],['/pj-clt-equivalente','Converter PJ em CLT equivalente']],validate:v=>n(v,'faturamento')<=0?'Informe o faturamento mensal.':'',calc:v=>{const revenue=n(v,'faturamento'),rate=n(v,'aliquota'),tax=revenue*rate/100,fixed=n(v,'contador')+n(v,'outros'),net=Math.max(0,revenue-tax-fixed);return {headline:money(net),summary:'Valor mensal estimado após a alíquota efetiva e os custos informados.',rows:[['Faturamento bruto',money(revenue)],['Impostos estimados',money(tax)],['Custos mensais',money(fixed)],['Percentual disponível',pct(revenue?net/revenue*100:0)]],note:'O QuantoLab não escolhe seu regime tributário. A alíquota efetiva precisa ser informada por você.'};}},
'mei-das':{fields:[['atividade','Atividade do MEI','select','servicos','','',null,null,'Valores oficiais de 2026.',['comercio','Comércio ou indústria, ICMS'],['servicos','Serviços, ISS'],['misto','Comércio e serviços, ICMS mais ISS'],['caminhoneiro-comercio','MEI Caminhoneiro, ICMS'],['caminhoneiro-servicos','MEI Caminhoneiro, ISS'],['caminhoneiro-misto','MEI Caminhoneiro, ICMS mais ISS']]],source:SOURCES.mei,related:[['/impostos-pj','Estimar impostos PJ'],['/pro-labore','Simular pró labore'],['/meta-faturamento','Planejar meta mensal']],calc:v=>{const map={comercio:82.05,servicos:86.05,misto:87.05,'caminhoneiro-comercio':195.52,'caminhoneiro-servicos':199.52,'caminhoneiro-misto':200.52},monthly=map[v.atividade]??86.05;return {headline:money(monthly),summary:'Valor mensal do DAS MEI de referência para 2026 conforme a atividade selecionada.',rows:[['DAS mensal',money(monthly)],['DAS em 12 meses',money(monthly*12)],['Salário mínimo de referência',money(1621)]]};}},
'pro-labore':{fields:[['valor','Pró labore bruto mensal','number',5000,'R$','',100,'monthlyIncome','Valor bruto definido para remuneração do sócio.'],['dependentes','Dependentes no IR','number',0,'','',1,null,'Dependentes considerados na retenção mensal.']],source:SOURCES.inss,related:[['/impostos-pj','Estimar custos PJ'],['/irrf','Conferir IRRF'],['/pj-clt-equivalente','Ver equivalente CLT']],validate:v=>n(v,'valor')<=0?'Informe o valor bruto do pró labore.':'',calc:v=>{const gross=n(v,'valor'),inss=Math.min(gross,8475.55)*.11,ir=irrfMonthly(gross,{inss,dependents:n(v,'dependentes')}),net=Math.max(0,gross-inss-ir.tax);return {headline:money(net),summary:'Pró labore líquido estimado considerando retenção previdenciária de 11% limitada ao teto e IRRF mensal.',rows:[['Pró labore bruto',money(gross)],['INSS estimado',money(inss)],['IRRF estimado',money(ir.tax)],['Líquido estimado',money(net)]],note:'Encargos da empresa e particularidades societárias ou tributárias não estão incluídos.'};}},
'custo-funcionario':{
  fields:[
    ['salario','Salário mensal','number',5000,'R$','',100,'monthlyIncome','Salário bruto mensal do funcionário.'],
    ['planoSaude','Plano de saúde','number',0,'R$','',50,null,'Custo mensal do plano pago pela empresa.'],
    ['valeTransporte','Vale transporte','number',0,'R$','',50,null,'Valor mensal disponibilizado pela empresa.'],
    ['valeRefeicao','Vale refeição','number',0,'R$','',50,null,'Valor mensal do benefício.'],
    ['outrosBeneficios','Outros benefícios','number',0,'R$','',50,null,'Some outros benefícios mensais pagos pela empresa.']
  ],source:SOURCES.methodology,related:[['/comparador-profissional','Comparar CLT e PJ'],['/fgts','Detalhar FGTS'],['/decimo-terceiro','Detalhar 13º']],
  validate:v=>n(v,'salario')<=0?'Informe o salário mensal.':'',
  calc:v=>{const salary=n(v,'salario'),health=n(v,'planoSaude'),transport=n(v,'valeTransporte'),meal=n(v,'valeRefeicao'),otherBenefits=n(v,'outrosBeneficios'),benefits=health+transport+meal+otherBenefits,thirteenth=salary/12,vacationBonus=salary/36,fgts=(salary+thirteenth+vacationBonus)*.08,monthly=salary+benefits+thirteenth+vacationBonus+fgts;return {headline:money(monthly),summary:'Custo mensal equivalente estimado em um modelo simplificado de contratação CLT.',rows:[['Salário mensal',money(salary)],['Plano de saúde',money(health)],['Vale transporte',money(transport)],['Vale refeição',money(meal)],['Outros benefícios',money(otherBenefits)],['Provisão de 13º',money(thirteenth)],['Provisão do adicional de férias',money(vacationBonus)],['FGTS estimado',money(fgts)]],table:{headers:['Componente','Valor mensal'],rows:[['Salário',money(salary)],['Plano de saúde',money(health)],['Vale transporte',money(transport)],['Vale refeição',money(meal)],['Outros benefícios',money(otherBenefits)],['13º proporcional mensal',money(thirteenth)],['1/3 de férias proporcional mensal',money(vacationBonus)],['FGTS estimado',money(fgts)],['Custo mensal equivalente',money(monthly)]]},note:'Esta é uma visão simplificada. Encargos patronais como INSS, RAT e terceiros variam conforme regime tributário, atividade e enquadramento da empresa.'};}
}
});
})();