(()=>{
'use strict';
const QL=window.QuantoLabTools;const {money,number,pct,n,compoundSeries}=QL.util;const SOURCES=QL.sources;
QL.register({
'reserva-emergencia':{fields:[['custos','Gastos essenciais por mês','number',4000,'R$','',100,'monthlyCosts','Considere apenas despesas realmente necessárias.'],['meses','Meses de proteção desejados','number',6,'',' meses',1,'reserveMonths','Ex.: 3, 6, 9 ou 12 meses.'],['atual','Quanto já tem reservado','number',5000,'R$','',100,null,'Valor disponível hoje para emergência.'],['prazo','Em quantos meses quer completar','number',12,'',' meses',1,null,'Usado para estimar o aporte mensal necessário.']],source:SOURCES.methodology,related:[['/metas-financeiras','Planejar uma meta'],['/juros-compostos','Simular aportes'],['/rendimento-cdi','Simular CDI']],validate:v=>n(v,'custos')<=0?'Informe seus gastos essenciais por mês.':'',calc:v=>{const costs=n(v,'custos'),months=n(v,'meses'),current=n(v,'atual'),target=costs*months,missing=Math.max(0,target-current),deadline=Math.max(1,n(v,'prazo')),monthly=missing/deadline;return {headline:money(target),summary:`Meta de reserva para ${number(months)} meses de gastos essenciais.`,rows:[['Reserva alvo',money(target)],['Já acumulado',money(current)],['Falta acumular',money(missing)],['Aporte mensal sem rendimento',money(monthly)]]};}},
'juros-compostos':{
  fields:[
    ['inicial','Valor inicial','number',10000,'R$','',100,null,'Valor disponível no início da simulação.'],
    ['aporte','Valor mensal','number',500,'R$','',50,null,'Valor adicionado ao fim de cada ciclo mensal.'],
    ['taxa','Taxa de juros','number',10,'','%',.1,null,'Informe a taxa usada na simulação.'],
    ['taxaTipo','Período da taxa','select','annual','','',null,null,'Escolha se a taxa informada é anual ou mensal.',['annual','Anual'],['monthly','Mensal']],
    ['periodo','Período','number',5,'','',1,null,'Informe a duração da simulação.'],
    ['periodoTipo','Unidade do período','select','years','','',null,null,'Escolha anos ou meses.',['years','Anos'],['months','Meses']]
  ],source:SOURCES.bcb,related:[['/metas-financeiras','Calcular tempo até uma meta'],['/rendimento-cdi','Simular CDI'],['/comparar-investimentos','Comparar investimentos']],
  validate:v=>n(v,'inicial')<=0&&n(v,'aporte')<=0?'Informe um valor inicial ou um valor mensal.':n(v,'periodo')<=0?'Informe o período da simulação.':'',
  calc:v=>{const initial=n(v,'inicial'),monthly=n(v,'aporte'),rate=n(v,'taxa'),period=n(v,'periodo'),months=Math.max(1,Math.floor(v.periodoTipo==='years'?period*12:period)),series=compoundSeries(initial,monthly,rate,v.taxaTipo,months),last=series.at(-1),invested=last?.invested??initial,gains=last?.totalInterest??0,future=last?.balance??initial;return {headline:money(future),summary:`Valor total estimado ao final de ${months} meses.`,rows:[['Valor total final',money(future)],['Valor total investido',money(invested)],['Total em juros',money(gains)]],table:{headers:['Indicador','Valor'],rows:[['Valor total final',money(future)],['Valor total investido',money(invested)],['Total em juros',money(gains)]]},series};}
},
'rendimento-cdi':{fields:[['valor','Valor aplicado','number',10000,'R$','',100,null,'Capital inicial.'],['cdi','CDI anual usado na simulação','number',14.15,'','% a.a.',.01,null,'Campo editável: confirme a taxa vigente antes de decidir.'],['percentual','Percentual do CDI do produto','number',100,'','% do CDI',1,null,'Ex.: 100%, 110% ou 120% do CDI.'],['meses','Prazo','number',12,'',' meses',1,null,'Prazo da simulação.'],['ir','IR sobre o rendimento','number',17.5,'','%',.1,null,'Informe a alíquota aplicável ao produto e prazo.']],source:SOURCES.bcb,related:[['/comparar-investimentos','Comparar com outra opção'],['/juros-compostos','Simular aportes'],['/metas-financeiras','Planejar uma meta']],validate:v=>n(v,'valor')<=0?'Informe o valor aplicado.':'',calc:v=>{const principal=n(v,'valor'),annual=n(v,'cdi')*(n(v,'percentual')/100),months=n(v,'meses'),gross=principal*Math.pow(1+annual/100,months/12),grossGain=Math.max(0,gross-principal),tax=grossGain*n(v,'ir')/100,net=gross-tax;return {headline:money(net),summary:`Valor líquido estimado usando ${pct(n(v,'percentual'))} do CDI e a taxa anual informada.`,rows:[['Taxa anual equivalente usada',pct(annual)],['Rendimento bruto',money(grossGain)],['IR estimado',money(tax)],['Valor final líquido',money(net)]],note:'O CDI anual foi deixado editável porque a taxa muda ao longo do tempo. Esta ferramenta não consulta cotação em tempo real.'};}},
'comparar-investimentos':{fields:[['valor','Valor inicial','number',10000,'R$','',100,null,'Mesmo valor aplicado nos dois cenários.'],['meses','Prazo','number',24,'',' meses',1,null,'Prazo igual para as duas opções.'],['taxaA','Rentabilidade anual, Opção A','number',12,'','% a.a.',.1,null,'Taxa anual estimada da opção A.'],['irA','IR sobre rendimento, A','number',17.5,'','%',.1,null,'Use 0 para produto isento.'],['taxaB','Rentabilidade anual, Opção B','number',10,'','% a.a.',.1,null,'Taxa anual estimada da opção B.'],['irB','IR sobre rendimento, B','number',0,'','%',.1,null,'Use 0 para produto isento.']],source:SOURCES.bcb,related:[['/rendimento-cdi','Detalhar CDI'],['/juros-compostos','Simular aportes'],['/metas-financeiras','Planejar meta']],validate:v=>n(v,'valor')<=0?'Informe o valor inicial.':'',calc:v=>{const principal=n(v,'valor'),months=n(v,'meses'),evaluate=(rate,ir)=>{const gross=principal*Math.pow(1+rate/100,months/12),gain=gross-principal;return gross-Math.max(0,gain)*ir/100;},a=evaluate(n(v,'taxaA'),n(v,'irA')),b=evaluate(n(v,'taxaB'),n(v,'irB')),diff=Math.abs(a-b),winner=a>=b?'Opção A':'Opção B';return {headline:winner,summary:`Diferença líquida estimada de ${money(diff)} ao final do prazo.`,rows:[['Opção A, valor líquido',money(a)],['Opção B, valor líquido',money(b)],['Diferença',money(diff)]]};}},
'metas-financeiras':{fields:[['meta','Meta financeira','number',50000,'R$','',100,null,'Valor que você quer alcançar.'],['atual','Valor atual','number',10000,'R$','',100,null,'Quanto já está acumulado.'],['aporte','Aporte mensal','number',1000,'R$','',50,null,'Quanto pretende adicionar por mês.'],['taxa','Rentabilidade anual estimada','number',8,'','% a.a.',.1,null,'Use 0 para uma projeção sem rendimento.']],source:SOURCES.methodology,related:[['/juros-compostos','Ver evolução dos juros'],['/reserva-emergencia','Planejar reserva'],['/rendimento-cdi','Simular CDI']],validate:v=>n(v,'meta')<=0?'Informe a meta financeira.':'',calc:v=>{const target=n(v,'meta'),current=n(v,'atual'),monthly=n(v,'aporte'),rate=n(v,'taxa');let months=0,value=current;const r=Math.pow(1+rate/100,1/12)-1;while(value<target&&months<1200){value=value*(1+r)+monthly;months++;if(monthly<=0&&r<=0)break;}const reached=value>=target;return {headline:reached?`${months} meses`:'Meta não alcançada',summary:reached?`Com os parâmetros informados, a meta é alcançada em aproximadamente ${Math.floor(months/12)} anos e ${months%12} meses.`:'Com o aporte e a taxa informados, a meta não é alcançada na janela da simulação.',rows:[['Meta',money(target)],['Valor projetado ao final',money(value)],['Aporte mensal',money(monthly)],['Prazo estimado',reached?`${months} meses`:'Não alcançado']]};}},
'inflacao':{fields:[['valor','Valor de referência hoje','number',5000,'R$','',100,null,'Quanto custa hoje o item ou orçamento analisado.'],['taxa','Inflação anual média estimada','number',4.5,'','% a.a.',.1,null,'Taxa hipotética para a projeção.'],['anos','Prazo','number',5,'',' anos',1,null,'Quantidade de anos.']],source:SOURCES.methodology,related:[['/metas-financeiras','Planejar meta corrigida'],['/juros-compostos','Comparar com rendimento'],['/reserva-emergencia','Revisar reserva']],validate:v=>n(v,'valor')<=0?'Informe o valor de referência.':'',calc:v=>{const value=n(v,'valor'),rate=n(v,'taxa'),years=n(v,'anos'),future=value*Math.pow(1+rate/100,years),increase=future-value;return {headline:money(future),summary:`Valor futuro equivalente se a inflação média for ${pct(rate)} por ${number(years)} anos.`,rows:[['Valor atual',money(value)],['Aumento nominal estimado',money(increase)],['Valor equivalente futuro',money(future)]]};}}
});
})();