(()=>{
'use strict';
const QL=window.QuantoLabTools;const {money,number,pct,n}=QL.util;const SOURCES=QL.sources;
QL.register({
'clientes-necessarios':{fields:[['meta','Meta de faturamento mensal','number',12000,'R$','',100,null,'Quanto você precisa faturar no mês.'],['ticket','Ticket médio por cliente','number',2500,'R$','',50,null,'Quanto cada cliente gera em média no mês.']],source:SOURCES.methodology,related:[['/meta-faturamento','Revisar meta mensal'],['/preco-projeto','Calcular preço de projeto'],['/margem-lucro','Calcular margem']],calc:v=>{const target=n(v,'meta'),ticket=Math.max(0.01,n(v,'ticket')),exact=target/ticket,clients=Math.ceil(exact);return {headline:`${clients} ${clients===1?'cliente':'clientes'}`,summary:`Você precisa de pelo menos ${clients} clientes nesse ticket médio para alcançar a meta informada.`,rows:[['Meta mensal',money(target)],['Ticket médio',money(ticket)],['Necessidade matemática',number(exact)],['Faturamento com clientes inteiros',money(clients*ticket)]]};}},
'margem-lucro':{fields:[['receita','Receita do período','number',20000,'R$','',100,null,'Faturamento usado na análise.'],['diretos','Custos diretos','number',6000,'R$','',50,null,'Custos ligados diretamente à entrega.'],['fixos','Custos fixos alocados','number',5000,'R$','',50,'monthlyCosts','Parcela de estrutura atribuída ao período.']],source:SOURCES.methodology,related:[['/preco-projeto','Revisar preço de projeto'],['/meta-faturamento','Revisar meta mensal'],['/clientes-necessarios','Calcular clientes necessários']],calc:v=>{const revenue=n(v,'receita'),costs=n(v,'diretos')+n(v,'fixos'),profit=revenue-costs,margin=revenue?profit/revenue*100:0;return {headline:pct(margin),summary:`Margem estimada com lucro de ${money(profit)} no período.`,rows:[['Receita',money(revenue)],['Custos totais',money(costs)],['Lucro',money(profit)],['Margem',pct(margin)]]};}},
'renda-anual':{fields:[['mensal','Renda bruta mensal','number',6000,'R$','',100,'monthlyIncome','Renda regular por mês.'],['meses','Meses recebidos','number',12,'',' meses',1,null,'Quantidade de meses com renda regular.'],['bonus','Bônus/PLR no ano','number',0,'R$','',100,null,'Valor bruto adicional anual.'],['decimo','Adicionar um 13º salário?','select','sim','','',null,null,'Útil para projeções CLT simples.',['sim','Sim'],['nao','Não']]],source:SOURCES.methodology,related:[['/salario-liquido','Calcular líquido mensal'],['/comparador-profissional','Comparar CLT e PJ'],['/meta-faturamento','Planejar meta']],calc:v=>{const monthly=n(v,'mensal'),months=n(v,'meses'),bonus=n(v,'bonus'),thirteenth=v.decimo==='sim'?monthly:0,total=monthly*months+bonus+thirteenth;return {headline:money(total),summary:'Renda bruta anual projetada com os componentes informados.',rows:[['Renda regular',money(monthly*months)],['13º incluído',money(thirteenth)],['Bônus/PLR',money(bonus)],['Total anual',money(total)]]};}},
'faturamento-anual':{fields:[['mensal','Faturamento médio mensal','number',12000,'R$','',100,'monthlyIncome','Média de receita bruta por mês.'],['meses','Meses faturados','number',12,'',' meses',1,null,'Meses com receita no ano.'],['impostos','Alíquota efetiva de impostos','number',10,'','%',0.1,'taxRate','Percentual efetivo sobre o faturamento.'],['custos','Custos fixos mensais','number',1500,'R$','',50,'monthlyCosts','Custos recorrentes do negócio.']],source:SOURCES.methodology,related:[['/meta-faturamento','Revisar meta mensal'],['/impostos-pj','Detalhar impostos PJ'],['/margem-lucro','Calcular margem']],calc:v=>{const monthly=n(v,'mensal'),months=n(v,'meses'),gross=monthly*months,taxes=gross*n(v,'impostos')/100,costs=n(v,'custos')*12,net=gross-taxes-costs;return {headline:money(net),summary:'Resultado anual estimado depois dos impostos e custos informados.',rows:[['Faturamento bruto anual',money(gross)],['Impostos estimados',money(taxes)],['Custos anuais',money(costs)],['Disponível estimado',money(net)]]};}}
});
})();
