(()=>{
'use strict';
const QL=window.QuantoLabTools;const {money,number,pct,clamp,n,irrfMonthly,cltPackageApprox,pjEquivalentClt}=QL.util;const SOURCES=QL.sources;
QL.register({
'pj-clt-equivalente':{fields:[['pj','Faturamento PJ por mês','number',10000,'R$','',100,'monthlyIncome','Valor bruto mensal do contrato PJ.'],['meses','Meses faturados por ano','number',12,'',' meses',1,null,'Reduza se houver meses sem faturamento.'],['impostos','Impostos efetivos sobre faturamento','number',10,'','%',0.1,'taxRate','Informe sua alíquota efetiva estimada.'],['custos','Custos PJ por mês','number',500,'R$','',50,'monthlyCosts','Contabilidade, ferramentas, plano de saúde e outros custos.']],source:SOURCES.methodology,related:[['/comparador-profissional','Comparar proposta CLT e PJ'],['/impostos-pj','Detalhar impostos PJ'],['/pro-labore','Simular pró-labore']],calc:v=>{const pj=n(v,'pj'),months=clamp(n(v,'meses',12),1,12),tax=n(v,'impostos'),costs=n(v,'custos'),annual=pj*months*(1-tax/100)-costs*12,clt=pjEquivalentClt(Math.max(0,annual));return {headline:money(clt),summary:'Salário CLT bruto mensal de referência cujo pacote anual aproximado se aproxima do valor PJ disponível informado.',rows:[['PJ disponível estimado no ano',money(annual)],['Pacote CLT anual aproximado',money(cltPackageApprox(clt))],['Equivalente CLT bruto mensal',money(clt)]],note:'É uma equivalência de pacote, não de dinheiro líquido. Benefícios, riscos, tributação e condições contratuais podem mudar a decisão.'};}},
'impostos-pj':{fields:[['faturamento','Faturamento mensal','number',10000,'R$','',100,'monthlyIncome','Receita bruta mensal usada na simulação.'],['aliquota','Alíquota efetiva estimada','number',10,'','%',0.1,'taxRate','Use sua alíquota efetiva real ou uma estimativa validada com sua contabilidade.'],['contador','Contabilidade por mês','number',250,'R$','',10,null,'Custo mensal do serviço contábil.'],['outros','Outros custos PJ','number',300,'R$','',10,'monthlyCosts','Ferramentas, taxas e despesas recorrentes.']],source:SOURCES.methodology,related:[['/pro-labore','Simular pró-labore'],['/mei-das','Ver DAS MEI'],['/pj-clt-equivalente','Converter PJ em CLT equivalente']],calc:v=>{const revenue=n(v,'faturamento'),rate=n(v,'aliquota'),tax=revenue*rate/100,fixed=n(v,'contador')+n(v,'outros'),net=Math.max(0,revenue-tax-fixed);return {headline:money(net),summary:'Valor mensal estimado após a alíquota efetiva e os custos informados.',rows:[['Faturamento bruto',money(revenue)],['Impostos estimados',money(tax)],['Custos mensais',money(fixed)],['Percentual disponível',pct(revenue?net/revenue*100:0)]],note:'O QuantoLab não escolhe seu regime tributário. A alíquota efetiva precisa ser informada por você.'};}},
'mei-das':{fields:[['atividade','Atividade do MEI','select','servicos','','',null,null,'Valores oficiais de 2026.',['comercio','Comércio/indústria — ICMS'],['servicos','Serviços — ISS'],['misto','Comércio e serviços — ICMS + ISS'],['caminhoneiro-comercio','MEI Caminhoneiro — ICMS'],['caminhoneiro-servicos','MEI Caminhoneiro — ISS'],['caminhoneiro-misto','MEI Caminhoneiro — ICMS + ISS']]],source:SOURCES.mei,related:[['/impostos-pj','Estimar impostos PJ'],['/pro-labore','Simular pró-labore'],['/meta-faturamento','Planejar meta mensal']],calc:v=>{const map={comercio:82.05,servicos:86.05,misto:87.05,'caminhoneiro-comercio':195.52,'caminhoneiro-servicos':199.52,'caminhoneiro-misto':200.52},monthly=map[v.atividade]??86.05;return {headline:money(monthly),summary:'Valor mensal do DAS-MEI de referência para 2026 conforme a atividade selecionada.',rows:[['DAS mensal',money(monthly)],['DAS em 12 meses',money(monthly*12)],['Salário mínimo de referência',money(1621)]]};}},
'pro-labore':{fields:[['valor','Pró-labore bruto mensal','number',5000,'R$','',100,'monthlyIncome','Valor bruto definido para remuneração do sócio.'],['dependentes','Dependentes no IR','number',0,'','',1,null,'Dependentes considerados na retenção mensal.']],source:SOURCES.inss,related:[['/impostos-pj','Estimar custos PJ'],['/irrf','Conferir IRRF'],['/pj-clt-equivalente','Ver equivalente CLT']],calc:v=>{const gross=n(v,'valor'),inss=Math.min(gross,8475.55)*0.11,ir=irrfMonthly(gross,{inss,dependents:n(v,'dependentes')}),net=Math.max(0,gross-inss-ir.tax);return {headline:money(net),summary:'Pró-labore líquido estimado considerando retenção previdenciária de 11% limitada ao teto e IRRF mensal.',rows:[['Pró-labore bruto',money(gross)],['INSS estimado',money(inss)],['IRRF estimado',money(ir.tax)],['Líquido estimado',money(net)]],note:'Encargos da empresa e particularidades societárias/tributárias não estão incluídos.'};}},
'custo-funcionario':{fields:[['salario','Salário bruto mensal','number',5000,'R$','',100,'monthlyIncome','Remuneração mensal contratual.'],['beneficios','Benefícios pagos pela empresa','number',1000,'R$','',50,null,'Vale, plano, auxílio e outros custos mensais.'],['encargos','Outros encargos patronais estimados','number',20,'','%',0.1,null,'Informe uma taxa compatível com o regime da empresa; varia muito.']],source:SOURCES.methodology,related:[['/comparador-profissional','Comparar CLT e PJ'],['/fgts','Detalhar FGTS'],['/decimo-terceiro','Detalhar 13º']],calc:v=>{const salary=n(v,'salario'),benefits=n(v,'beneficios'),chargesRate=n(v,'encargos'),thirteenth=salary/12,vacationBonus=salary/36,fgts=(salary+thirteenth+vacationBonus)*0.08,other=salary*chargesRate/100,monthly=salary+benefits+thirteenth+vacationBonus+fgts+other;return {headline:money(monthly),summary:'Custo mensal equivalente estimado com provisões básicas e a taxa patronal informada.',rows:[['Salário',money(salary)],['Benefícios',money(benefits)],['Provisão mensal de 13º',money(thirteenth)],['Provisão mensal do adicional de férias',money(vacationBonus)],['FGTS aproximado',money(fgts)],['Outros encargos informados',money(other)]],note:'Não é folha oficial. RAT, terceiros, benefícios, convenções, substituições e regimes tributários podem alterar o custo real.'};}}
});
})();
