from pathlib import Path
from html import escape as E
R=Path(__file__).resolve().parents[1]
T={
'salario-liquido':('Salário Líquido 2026','Calcule seu salário líquido em 2026','Estime o valor disponível após INSS, IRRF e descontos informados.','A conta usa as faixas progressivas de INSS e as regras mensais de IRRF de 2026.'),
'ferias':('Férias 2026','Calcule o valor das suas férias','Estime remuneração proporcional e adicional constitucional de 1/3.','A referência combina remuneração adquirida no período e o adicional de 1/3.'),
'decimo-terceiro':('13º Salário 2026','Calcule seu 13º salário','Veja o valor bruto proporcional pelos meses elegíveis no ano.','Cada mês com 15 dias ou mais trabalhados corresponde a 1/12 na referência.'),
'fgts':('FGTS 2026','Estime seus depósitos de FGTS','Veja referências mensal e acumulada para o FGTS.','A ferramenta usa a alíquota geral de 8% para vínculo CLT comum.'),
'seguro-desemprego':('Seguro-Desemprego 2026','Estime o Seguro-Desemprego','Use média salarial, tempo trabalhado e histórico de solicitações.','A ferramenta aplica as faixas de 2026 e estima a quantidade potencial de parcelas.'),
'hora-extra':('Hora Extra 2026','Calcule o valor da hora extra','Converta salário e jornada em valor-hora e aplique o adicional informado.','A referência parte da hora normal e adiciona o percentual de hora extra informado.'),
'inss':('INSS 2026','Calcule sua contribuição ao INSS','Veja a contribuição progressiva estimada conforme a modalidade.','Para empregado, cada faixa incide somente sobre a parcela de salário correspondente.'),
'irrf':('IRRF 2026','Calcule o IRRF mensal','Estime a retenção mensal usando as regras de 2026.','A ferramenta compara deduções legais e simplificada e aplica a redução vigente em 2026.'),
'pj-clt-equivalente':('PJ para CLT Equivalente','Converta renda PJ em referência CLT','Compare o valor anual PJ com um pacote CLT aproximado.','A equivalência considera salário, 13º, adicional de férias e FGTS como referência de pacote.'),
'impostos-pj':('Impostos PJ','Estime impostos e custos PJ','Aplique sua alíquota efetiva e custos recorrentes ao faturamento.','O QuantoLab não presume regime tributário: a alíquota efetiva é informada por você.'),
'mei-das':('DAS MEI 2026','Consulte a referência do DAS MEI','Veja o valor mensal de 2026 conforme a atividade selecionada.','A referência combina contribuição previdenciária e ICMS/ISS quando aplicáveis.'),
'pro-labore':('Pró-labore','Estime o líquido do pró-labore','Simule INSS e IRRF sobre uma remuneração de sócio.','É uma estimativa informativa e não substitui a apuração contábil da empresa e do sócio.'),
'custo-funcionario':('Custo de Funcionário','Estime o custo mensal de um funcionário','Combine salário, benefícios, provisões e encargos informados.','O resultado organiza componentes de custo e deixa a taxa patronal ajustável.'),
'clientes-necessarios':('Clientes Necessários','Descubra quantos clientes precisa no mês','Transforme sua meta de faturamento em quantidade de clientes.','A meta é dividida pelo ticket médio e arredondada para cima.'),
'margem-lucro':('Margem de Lucro','Calcule a margem do seu trabalho','Compare receita, custos e lucro em reais e percentual.','Receita menos custos gera o lucro; a margem mostra quanto da receita permanece.'),
'reserva-emergencia':('Reserva de Emergência','Planeje sua reserva de emergência','Transforme gastos essenciais em uma meta de meses de proteção.','A meta combina gasto essencial mensal e quantidade de meses escolhida.'),
'juros-compostos':('Juros Compostos','Simule juros compostos','Projete valor inicial e aportes mensais ao longo do tempo.','A taxa anual informada é convertida em equivalente mensal para a projeção.'),
'rendimento-cdi':('Rendimento CDI','Simule um investimento atrelado ao CDI','Informe CDI de referência e percentual do CDI do produto.','O CDI fica editável porque muda ao longo do tempo; a ferramenta não consulta taxa ao vivo.'),
'comparar-investimentos':('Comparar Investimentos','Compare dois cenários de investimento','Coloque duas taxas lado a lado usando o mesmo valor e prazo.','A comparação usa a mesma base matemática e destaca a diferença líquida estimada.'),
'metas-financeiras':('Meta Financeira','Calcule o prazo de uma meta financeira','Combine valor atual, aportes e rentabilidade estimada.','A simulação mostra aproximadamente quantos meses seriam necessários para alcançar a meta.'),
'inflacao':('Impacto da Inflação','Veja o efeito da inflação no poder de compra','Projete um valor usando uma inflação anual hipotética.','É um cenário matemático, não uma previsão de inflação futura.'),
'renda-anual':('Renda Anual','Transforme renda mensal em visão anual','Some meses recebidos, 13º e bônus informados.','A visão anual ajuda a comparar propostas que não têm a mesma estrutura mensal.'),
'faturamento-anual':('Faturamento Anual','Projete seu faturamento no ano','Combine receita mensal, meses ativos, impostos e custos.','O resultado mostra faturamento bruto e disponibilidade estimada após os itens informados.')}
G={'tools-clt.js':{'salario-liquido','ferias','decimo-terceiro','fgts','seguro-desemprego','hora-extra','inss','irrf'},'tools-pj.js':{'pj-clt-equivalente','impostos-pj','mei-das','pro-labore','custo-funcionario'},'tools-freela.js':{'clientes-necessarios','margem-lucro','renda-anual','faturamento-anual'},'tools-finance.js':{'reserva-emergencia','juros-compostos','rendimento-cdi','comparar-investimentos','metas-financeiras','inflacao'}}
def group(s):
 for f,x in G.items():
  if s in x:return f

def H(path,title,desc,robots='index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'):
 u='https://quantolab.com.br/'+path.lstrip('/')
 return f'''<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | QuantoLab</title><meta name="description" content="{E(desc)}"><link rel="canonical" href="{u}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta name="robots" content="{robots}"><meta name="theme-color" content="#D9FF66"><meta property="og:locale" content="pt_BR"><meta property="og:type" content="website"><meta property="og:site_name" content="QuantoLab"><meta property="og:title" content="{E(title)} | QuantoLab"><meta property="og:description" content="{E(desc)}"><meta property="og:url" content="{u}"><meta name="twitter:card" content="summary"><script type="application/ld+json">{{"@context":"https://schema.org","@type":"WebPage","name":"{E(title)}","url":"{u}"}}</script><script src="/theme.js"></script><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/calculator-simple.css"><link rel="stylesheet" href="/theme.css"><link rel="stylesheet" href="/platform.css"></head>'''
HEADER='<header class="header"><div class="shell nav"><a class="brand" href="/" aria-label="QuantoLab"><img src="/quantolab-logo.svg" alt="QuantoLab" width="333" height="51"></a><nav class="navlinks" aria-label="Navegação principal"><a href="/ferramentas">Ferramentas</a><a href="/metodologia">Metodologia</a><a href="/sobre">Sobre</a></nav></div></header>'
FOOT='<footer class="footer"><div class="shell footer-grid"><div class="footer-brand"><img src="/quantolab-logo.svg" alt="QuantoLab" width="333" height="51"><span>Ferramentas claras para decisões profissionais.</span></div><div class="footer-links"><a href="/ferramentas">Ferramentas</a><a href="/metodologia">Metodologia</a><a href="/politica-de-privacidade">Privacidade</a><a href="/termos">Termos</a></div></div></footer>'
for s,(t,h,d,logic) in T.items():
 scripts=f'<script src="/tools-core.js"></script><script src="/{group(s)}"></script>'
 html=f'''<!doctype html><html lang="pt-BR">{H(s,t,d)}<body class="calculator-simple" data-tool="{s}">{HEADER}<main><section class="calc-hero"><div class="shell"><div class="breadcrumbs"><a href="/">QuantoLab</a> / <a href="/ferramentas">Ferramentas</a> / {E(t)}</div><h1>{E(h)}</h1><p class="lead">{E(d)}</p></div></section><div class="shell"><div class="trust-row trust-row--compact" aria-label="Compromissos do QuantoLab"><span>Sem cadastro</span><span>Cálculo no navegador</span><a href="/metodologia">Como calculamos →</a></div><section class="calc-grid"><div class="panel form dynamic-tool-form" data-tool-form><p class="simple-start"><strong>Comece pelo essencial.</strong> Ajuste os valores e recalcule quando quiser.</p></div><aside class="panel result" aria-live="polite" data-tool-result><div class="result-top"><div class="result-kicker">Resultado estimado</div><div class="result-value" data-result-headline>—</div><p class="result-sub" data-result-summary></p></div><div class="result-body"><details class="result-details"><summary>Como chegamos neste resultado</summary><div class="result-details-body" data-result-rows></div></details><p class="result-note" data-result-note hidden></p><div class="result-share"><button class="btn btn-secondary" type="button" data-share-result>Compartilhar</button><button class="btn btn-secondary" type="button" data-copy-result>Copiar link</button></div></div></aside></section><article class="article"><h2>Como interpretar esta estimativa</h2><p>{E(logic)}</p><div class="notice"><strong>Importante:</strong> é uma referência informativa. Condições individuais podem alterar o valor real.</div></article><div class="source-note" role="note" data-source></div><section class="next-decision" aria-labelledby="next-decision-title"><div class="next-decision__head"><span class="eyebrow">Continue sua jornada</span><h2 id="next-decision-title">Qual é a próxima decisão?</h2></div><div class="card-grid decision-grid" data-related-tools></div></section></div></main>{FOOT}{scripts}</body></html>'''
 (R/f'{s}.html').write_text(html)
EX={'valor-hora':('Valor por hora','Descubra quanto cobrar por hora.'),'preco-projeto':('Preço de projeto','Transforme horas e custos em preço.'),'meta-faturamento':('Meta mensal','Planeje quanto precisa faturar.'),'comparador-profissional':('CLT x PJ','Compare propostas e ponto de equilíbrio.'),'simulador':('Rescisão CLT','Estime valores de desligamento.')}
L={s:(v[0],v[2]) for s,v in T.items()}|EX
J={'CLT':['salario-liquido','ferias','decimo-terceiro','fgts','seguro-desemprego','hora-extra','inss','irrf','comparador-profissional','simulador'],'PJ':['pj-clt-equivalente','impostos-pj','mei-das','pro-labore','custo-funcionario'],'Freelancer':['valor-hora','preco-projeto','meta-faturamento','clientes-necessarios','margem-lucro','renda-anual','faturamento-anual'],'Financeiro':['reserva-emergencia','juros-compostos','rendimento-cdi','comparar-investimentos','metas-financeiras','inflacao']}
sects=[]
for j,ss in J.items():
 cards=''.join(f'<a class="tool-card tool-card--compact" href="/{s}"><span class="num">{i:02}</span><h3>{E(L[s][0])}</h3><p>{E(L[s][1])}</p><span class="tool-link">Abrir</span></a>' for i,s in enumerate(ss,1))
 sects.append(f'<section class="journey-section"><div class="journey-section__head"><h2>{j}</h2><p>Ferramentas conectadas para decisões de {j.lower()}.</p></div><div class="tool-grid tool-grid--dense">{cards}</div></section>')
(R/'ferramentas.html').write_text(f'<!doctype html><html lang="pt-BR">{H("ferramentas","Ferramentas","Explore 28 ferramentas do QuantoLab organizadas por decisões de trabalho, carreira e dinheiro.")}<body>{HEADER}<main><div class="shell"><section class="catalog-hero"><span class="eyebrow">28 ferramentas conectadas</span><h1>Comece pela decisão que você precisa tomar</h1><p class="lead">Cada ferramenta funciona sozinha e conecta a próximos cálculos quando isso ajuda.</p></section>{"".join(sects)}</div></main>{FOOT}</body></html>')
(R/'meus-numeros.html').write_text(f'''<!doctype html><html lang="pt-BR">{H('meus-numeros','Meus números','Salve referências opcionais apenas neste navegador para preencher calculadoras mais rápido.')}<body>{HEADER}<main><div class="shell"><section class="legal-hero"><h1>Meus números</h1><p class="lead">Referências opcionais salvas somente neste navegador.</p></section><section class="panel form"><div class="profile-grid">{''.join(f'<div class="field"><label for="{i}">{l}</label><div class="input-wrap"><input id="{i}" type="number" min="0" inputmode="decimal"></div></div>' for i,l in [('profileMonthlyIncome','Renda desejada por mês'),('profileMonthlyCosts','Custos mensais'),('profileHoursDay','Horas por dia'),('profileDaysWeek','Dias por semana'),('profileTaxRate','Alíquota PJ de referência (%)'),('profileReserveMonths','Meses de reserva')])}</div><div class="profile-actions"><button class="btn" id="profileSave" type="button">Salvar neste navegador</button><button class="btn btn-secondary" id="profileClear" type="button">Apagar meus números</button></div><p id="profileStatus" class="local-data-note" aria-live="polite">Nenhum dado é obrigatório.</p></section></div></main>{FOOT}<script src="/profile.js"></script></body></html>''')
P={'designer':'Designer','desenvolvedor':'Desenvolvedor','copywriter':'Copywriter','social-media':'Social Media','fotografo':'Fotógrafo','arquiteto':'Arquiteto'}
D=R/'valor-hora';D.mkdir(exist_ok=True)
for s,nm in P.items():
 desc=f'Entenda o que considerar ao calcular valor por hora para {nm.lower()} e use seus próprios custos, tempo e meta.'
 D.joinpath(s+'.html').write_text(f'<!doctype html><html lang="pt-BR">{H("valor-hora/"+s,"Valor por hora para "+nm,desc)}<body>{HEADER}<main><div class="shell"><section class="legal-hero"><h1>Valor por hora para {nm}</h1><p class="lead">{E(desc)}</p></section><article class="article"><h2>Use sua realidade, não uma média isolada</h2><p>Considere pesquisa, produção, revisões, comunicação, tarefas não faturáveis, custos e risco do escopo. A referência por hora deve ser validada depois no preço do projeto.</p><div class="notice"><strong>Próximo passo:</strong> use a calculadora principal com seus próprios números.</div><p><a class="btn" href="/valor-hora">Abrir calculadora de valor por hora →</a></p></article></div></main>{FOOT}</body></html>')
print('generated',len(T),'new calculators')

# Keep generated pages aligned with the public editorial and AdSense readiness policy.
if __name__ == '__main__':
 import subprocess, sys
 subprocess.run([sys.executable, str(R/'scripts'/'prepare-adsense-review.py'), '--post-generate'], check=True)
